### ISSUE TITLE
Define Vision

### ISSUE THREAD

**Issue by thiagodiasads** [thiagodiasads/yolo-bug-fixes#1]

**Comment by CristianeMarques** [comment]
Jservice

Problema:
O problema é a falha na comunicação e na falta de organização dos registros das ordens de serviço.

Envolvidos:
Usuário
Cliente
Equipe de manutenção
Concorrentes 
Professor

Característica principal:
Realiza registro de ordens de serviço.

**Comment by masmangan** [comment]
Colocar a visão em um documento no repositório.
Fechar o incidente quando terminado.

**Comment by CristianeMarques** [comment]
Os documentos estão no note
