### ISSUE TITLE
Criar a Classe de Conexão com o Banco de Dados para Classe OrdemDeServico

### ISSUE THREAD

**Issue by shluh** [thiagodiasads/yolo-bug-fixes#15]
Implementar a classe de conexão com Banco de Dados com os atributos, a principio, da Classe OrdemDeServico

**Comment by thiagodiasads** [comment]
Decidir entre DAO/JDBC ou Hibernate.

**Comment by thiagodiasads** [comment]
Criar arquivo de Properties e salvar no repositório.
