### ISSUE TITLE
Criar o Banco de Dados para o projeto JService

### ISSUE THREAD

**Issue by shluh** [thiagodiasads/yolo-bug-fixes#17]
O Banco de Dados a ser usado será o postgreSql (pgAdmin III)

**Comment by thiagodiasads** [comment]
Escolher entre PG , MySql e SqLite.

**Comment by thiagodiasads** [comment]
Tabelas:
Clientes;
Equipamentos;
Ordens de Serviço.

**Comment by thiagodiasads** [comment]
Cadastrar cliente com código: 1 para testes.

**Comment by thiagodiasads** [comment]
Cadastrar equipamento com código: 1, para testes.

**Comment by thiagodiasads** [comment]
Fazer script em .Sql e guardar no repositório.

**Comment by thiagodiasads** [comment]
Instalando MySqlServer.

**Comment by thiagodiasads** [comment]
Instalando MySql Workbench.

**Comment by thiagodiasads** [comment]
Criada a tabela Clientes.

**Comment by thiagodiasads** [comment]
Criado no BD na tabela Clientes um cliente com código 1 para testes:
codigocliente: 1,
nomecliente: Marco Mangan,
emailcliente: marco.mangan@gmail.com,
cpfcliente: 11122233344.

**Comment by thiagodiasads** [comment]
Criada a tabela Equipamentos.

**Comment by thiagodiasads** [comment]
Criado no BD na tabela Equipamentos um equipamento com código 1 para testes:
codigoequipamento: 1,
marcaequipamento: HP,
modeloequipamento: G42,
serialequipamento: ABC123DEF.

**Comment by thiagodiasads** [comment]
Criada a tabela Ordens de Serviço.
