### ISSUE TITLE
Write User Story

### ISSUE THREAD

**Issue by thiagodiasads** [thiagodiasads/yolo-bug-fixes#2]

**Comment by CristianeMarques** [comment]
Histórias de Usuário
- Login no sistema
  Usuário informa login e senha. Sistema valida a senha e busca perfil do usuário para listar os itens no menu.
- Registrar Ordem de Serviço
  Usuário seleciona cliente, tipo de equipamento, fabricante, modelo, identificação do equipamento (serial), data de abertura, descrição do defeito.
- Cadastrar cliente
  Cadastrar dados de identificação do cliente: nome, endereço, cpf, telefones de contato, e-mail.
- Cadastrar fabricante
  Cadastrar nome fantasia do fabricante e dados de contato dos representantes e fornecedores de peças.
- Cadastrar peças para cada tipo de equipamento
  Cadastrar as peças que podem ser substituídas por tipo de equipamento e vincular a fornecedores.
- Cadastrar Tipos de Equipamentos
  Cadastros os tipos de equipamentos em que a empresa faz manutenção.
- Cadastrar Tipos de Defeitos
  Equipamento não liga, trava, aquece demais, faz barulho...
- Listar Ordens de Serviço aguardando triagem
  Permitir ao técnico listar as ordens de serviço com status de triagem e ordenar pela data de abertura da ordem de serviço.
- Registrar pedido de peça
  Permitir ao técnico registrar pedido de peça para o fornecedor e vincular o pedido à ordem de serviço.
- Listar peças com pedidos de fornecimento ainda não realizados
  Relatório de peças que aguardam o recebimento pelos fornecedores
- Registrar recebimento de peças
  Permitir ao responsável pelo almoxarifado registrar o recebimento de peças para realização de serviço.
- Listar Ordens de Serviço não autorizadas
  Permitir ao técnico classificas as ordens de serviço não autorizadas para preparar o equipamento para devolução ao cliente.
- Registrar recebimento de peças no andamento da ordem de serviço
  O sistema deve registrar no histórico da ordem de serviço o recebimento de cada peça necessária ao serviço e, caso todas as peças tenham sido recebidas, alterar a situação para em serviço
- Enviar e-mail para o cliente solicitando autorização para o serviço
  O sistema deve enviar e-mail para o cliente com o resumo da ordem de serviço e o orçamento e peças que serão substituídas, solicitando que entre em contato para autorizar o serviço.
- Registrar orçamento na ordem de serviço
  O técnico deve registrar no histórico o orçamento e as peças que serão substituídas e alterar a situação da ordem de serviço para aguarda autorização.
- Registrar conclusão da ordem de serviço
  O técnico deve registrar no histórico a conclusão da ordem de serviço com laudo dos testes realizados e alterar a situação para “concluída"
- Listar ordens de serviço concluídas para fins de faturamento
  Relatório das ordens de serviço concluídas mas ainda não faturadas.
- Registrar pagamento das ordens de serviço
  Registrar no histórico da ordem de serviço as formas de pagamento e os pagamentos realizados.
- Recuperar senha de usuário
  Permitir ao usuário gerar uma nova senha e enviar para o e-mail que estiver em seu cadastro.
- Alterar dados de usuário
  Permitir ao usuário alterar os dados: senha, e-mail, nome, perfil.

**Comment by masmangan** [comment]
Colocar as histórias em um documento no repositório.
Fechar o incidente quando completado.

**Comment by CristianeMarques** [comment]
Os documentos estão no note
