### ISSUE TITLE
Define Iteration

### ISSUE THREAD

**Issue by CristianeMarques** [thiagodiasads/yolo-bug-fixes#3]
Cristiane (Customer)
        13/03/2014  Definir visão  
        20/03/2014  Definir histórias de usuário  
        27/03/2014  Início do desenvolvimento da tela de cadastro de cliente  
        03/04/2014  Entrega da tela de cadastro de clientes

Thiago (Programmer admin)  
       13/03/2014  Criar repositório
        20/03/2014  Adaptar o ambiente de programação 
        27/03/2014  Início do desenvolvimento da tela de registro de ordem serviço  
        03/04/2014  Entrega parcial da tela de ordem de serviço

Shirlei (Coach)  
        13/03/2014  Adaptar o processo  
        20/03/2014  Explicar o processo  
        27/03/2014  Início do desenvolvimento da tela de cadastro de equipamentos
        03/04/2014  Entrega da tela de cadastro de equipamentos

**Comment by thiagodiasads** [comment]
Cris, eu preciso que tu te cadastre no Trello e confirme teu nome de
cadastro ou e-mail pra eu te adicionar na board do nosso projeto!

Em 27 de março de 2014 07:09, CristianeMarques
notifications@github.comescreveu:

**Comment by masmangan** [comment]
Meu usuário no Trello é masmangan.
Criar documento com o plano e encerrar o incidente quando completado.

**Comment by thiagodiasads** [comment]
Longe de mim querer corrigir nosso mestre e ilustre "Collaborator" masmangan, mas seu usuário no Trello é na verdade: marcomangan. Tenho certeza que isso não foi um erro e sim um processo didático pedagógico afim de avaliar a real compreensão e interesse da equipe em desempenhar as tarefas propostas.

**Comment by masmangan** [comment]
De fato. Precisamos de pessoas atentas e que saibam contornar pequenos obstáculos, tudo isso e ainda sabendo lidar com pessoas difíceis. :)

**Comment by CristianeMarques** [comment]
Está sendo usado integração entre Trello, zapier e git.
