### ISSUE TITLE
Programar persistência para a história Registrar Ordem de Serviço

### ISSUE THREAD

**Issue by masmangan** [thiagodiasads/yolo-bug-fixes#8]

**Comment by thiagodiasads** [comment]
Criar o método gravarOrdem (obj Ordem de Serviço) para gravar uma ordem de serviço no BD, dado um objeto Ordem de Serviço. Usar classe de conexão e usar prepared statement.

**Comment by shluh** [comment]
Já foi criado o método gravarOrdem e usado o prepared statement (como comentário no código). Porém o incidente ainda não será encerrado pois dependo da conclusão da tarefa #30 e #15 para não  dar erro no método.

**Comment by shluh** [comment]
Criar BD
Testar SQL 
Programar método
